---
# OpenBSD dhcpd Playbook 
# ----------------------
#
# This playbook deploys the dhcpd.conf file and 
# configures the dhcpd service for the al1 
# analysis lab.
# 


- name: dhcpd Playbook
  hosts: dhcp
  become: yes
  become_method: doas
  become_user: root
  
  tasks:

    - name: Deploy dhcpd.conf template 
      ansible.builtin.template:
        src: "{{ inventory_dir }}/templates/dhcpd.conf.j2"
        dest: /etc/dhcpd.conf
      register: dhcpd
  
    - name: Restart dhcpd configuration (changed)
      ansible.builtin.service:
        name: dhcpd
        state: reloaded 
      when: dhcpd.changed

    - name: Enable / Start dhcpd
      ansible.builtin.service:
        name: dhcpd
        enabled: yes
        state: started
        args: em1
        use: "rcctl"

