---
# OpenBSD DHCPd Playbook 
# ----------------------
#
# This playbook deploys the dhcpd.conf file and 
# configures the dhcpd service for the al1 
# analysis lab.
# 


- name: DHCPd Playbook
  hosts: dhcp
  become: yes
  become_user: root
  
  tasks:
    - name: Deploy dhcpd.conf template 
      ansible.builtin.template:
        src: "{{ inventory_dir }}/templates/dhcpd.conf.j2"
        dest: /etc/dhcpd.conf
      
    - name: Enable dhcpd
      ansible.builtin.command: /usr/sbin/rcctl enable dhcpd

    - name: Set dhcpd flags
      ansible.builtin.command: "/usr/sbin/rcctl set dhcpd flags {{ al1_dhcpd_interface }}" 
             
