---
# OpenBSD NTPD Configuration
#
# This playbook configures ntp server or client for OpenBSD machines.
# The ntpd.conf configuration determines the ntp functionality.
#
#

- name: OpenBSD NTP Configuration
  hosts: ntpd
  become: yes
  become_user: root 

  tasks:

    - name: Stop NTP
      ansible.builtin.service:
        name: ntpd
        enabled: yes
        state: stopped
        use: "rcctl"

    - name: Copy ntp.conf template
      ansible.builtin.template:
        src: "{{ inventory_dir }}/templates/ntpd.conf.j2"
        dest: /etc/ntpd.conf
        owner: root
        group: wheel
        mode: '0644'

    - name: Start NTP
      ansible.builtin.service:
        name: ntpd
        enabled: yes
        state: started
        use: "rcctl"

